<h1>
   CRUD With Zend and Doctrine
</h1>

<table border="1" cellspacing="0" cellpadding="2">
    <tr>
        <td>Id</td>
        <td>Username</td>
        <td>Password</td>
        <td>Role</td>
    </tr>
    <?php foreach($this->users as $user):?>
    <tr>
        <td><?php echo $user->id?></td>
        <td><?php echo $user->username?></td>
        <td><?php echo $user->password?></td>
        <td><?php echo $user->Role->name?></td>
    </tr>
    <?php endforeach?>
</table>